# Generated by Django 4.2.8 on 2024-04-11 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.RenameField(
            model_name='billcategory',
            old_name='post',
            new_name='bill',
        ),
        migrations.RemoveField(
            model_name='category',
            name='subscribers',
        ),
    ]
